# Travis-CI Config file
os: linux

dist: focal

language: python

# The test will run on the given python versions
python: 
  - "3.9" 

# Installing all the dependencies before testing
install:
  - pip3 install -r requirements.txt

# Commands to be executed before script
before_script:
  - cd src/

# Test command
script:
  - python3 Scraper.py
  - python3 Errors.py
